name: Build Package

on:
  push:

jobs:
  build:
    name: Conda setup, build, install and run the package
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        conda-version: "24.11.2"
        environment-file: environment.yml
        activate-environment: mle_dev

    - name: Configure 'defaults' channel explicitly in Conda and activate environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda config --add channels defaults
        conda activate mle_dev

    - name: Install tree CLI tool
      run: sudo apt-get install tree

    - name: Display directory tree before building
      run: tree -d

    - name: Build package
      run: |
        pip install build
        python -m build .
        echo "Building the package..."

    - name: Display directory tree after building
      run: tree -d

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/*
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./dist

    - name: Install the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate mle_dev
        pip install ./dist/*.whl  

    - name: Run tests with pytest
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate mle-dev
        pip install pytest
        pytest --disable-warnings -q
        pytest tests/unit_tests/test_file.py
