name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Miniconda with Custom Installer
      uses: conda-incubator/setup-miniconda@v3  # Miniconda setup
      with:
        installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh  # Use custom installer URL from conda-forge
        activate-environment: mle_dev  # Custom environment name
        python-version: '3.12.4'  # Python version aligned with your environment
        environment-file: environment.yml  # Point to your environment file
        auto-activate-base: false  # Do not auto-activate base Conda environment
        allow-softlinks: true  # Allow softlinks
        show-channel-urls: true  # Show channel URLs
    - name: Display Conda Info
      run: |
        conda info  # Show basic conda information
        conda list  # List installed packages
        conda config --show-sources  # Show conda configuration sources
        conda config --show  # Show current conda config
    -  run: |
        conda activate mle_dev
        flake8 .
    - name: Run nonstandardcode.py
      run: python nonstandardcode.py  # Execute your Python script
